(()=>{'use strict';
const $=id=>document.getElementById(id),C=$('game'),X=C.getContext('2d'),stage=$('stage'),GW=12,GH=12,SAVE='dead-grid-profile-v3',DEV='NEON8';
const ROUTES=[
[[0,2],[1,2],[2,2],[2,3],[3,3],[4,3],[4,4],[5,4],[6,4],[6,5],[7,5],[8,5],[8,6],[9,6],[10,6],[10,7],[11,7]],
[[0,7],[1,7],[1,6],[2,6],[3,6],[3,5],[4,5],[5,5],[5,4],[6,4],[7,4],[7,3],[8,3],[9,3],[9,4],[10,4],[11,4]],
[[0,4],[1,4],[1,5],[2,5],[2,6],[3,6],[4,6],[4,7],[5,7],[6,7],[6,6],[7,6],[7,5],[8,5],[9,5],[9,4],[10,4],[11,4]],
[[0,8],[1,8],[2,8],[2,7],[3,7],[3,6],[4,6],[5,6],[5,5],[5,4],[6,4],[7,4],[7,5],[8,5],[9,5],[9,6],[10,6],[11,6]],
[[0,1],[1,1],[1,2],[2,2],[3,2],[3,3],[4,3],[5,3],[5,4],[5,5],[6,5],[7,5],[7,6],[8,6],[9,6],[9,7],[10,7],[11,7]]];
const chars=[
{id:1,name:'CHARACTER 1',role:'Pulse Assault',cost:60,unlock:0,color:'#ff3ec8',range:2.45,damage:9,rate:.38,weapon:'pulse',tree:[['OVERDRIVE','Fire rate +30%','rate',70],['ION ROUNDS','Damage +45%','damage',70]]},
{id:2,name:'CHARACTER 2',role:'Arc Sniper',cost:95,unlock:0,color:'#6dffef',range:3.8,damage:27,rate:1.25,weapon:'laser',tree:[['DEAD EYE','Range +25%','range',80],['RAIL CORE','Damage +60%','damage',80]]},
{id:3,name:'CHARACTER 3',role:'Nova Tech',cost:80,unlock:0,color:'#ff9d31',range:2,damage:18,rate:1.45,splash:1.1,weapon:'explosive',tree:[['WIDE NOVA','Blast radius +45%','splash',75],['HOT CORE','Damage +50%','damage',75]]},
{id:4,name:'CHARACTER 4',role:'Volt Warden',cost:105,unlock:1000,color:'#9b62ff',range:2.7,damage:17,rate:.72,weapon:'arc',tree:[['CHAIN','Range +20%','range',95],['SURGE','Damage +50%','damage',95]]},
{id:5,name:'CHARACTER 5',role:'Photon Monk',cost:115,unlock:2500,color:'#ffe73c',range:2.2,damage:21,rate:.65,weapon:'pulse',tree:[['FOCUS','Range +25%','range',105],['FLARE','Damage +50%','damage',105]]},
{id:6,name:'CHARACTER 6',role:'Crimson Gear',cost:130,unlock:5000,color:'#ff455d',range:2.8,damage:30,rate:1.05,weapon:'explosive',tree:[['TURBO','Fire rate +30%','rate',120],['REDLINE','Damage +50%','damage',120]]},
{id:7,name:'CHARACTER 7',role:'Bio Spark',cost:145,unlock:8500,color:'#38ff7d',range:3,damage:25,rate:.82,weapon:'arc',tree:[['SPORE','Range +25%','range',130],['MUTAGEN','Damage +50%','damage',130]]},
{id:8,name:'CHARACTER 8',role:'Zero Vector',cost:170,unlock:12000,color:'#43a5ff',range:4,damage:42,rate:1.3,weapon:'laser',tree:[['HORIZON','Range +25%','range',150],['SINGULAR','Damage +60%','damage',150]]}];
let profile=load(),path=ROUTES[0],pathSet=new Set(path.map(p=>p.join(','))),routeIndex=0,power,core,maxCore,coreLevel,chapter,wave,defenders,enemies,spawnQ,running,paused,ended,selected=null,selectedCard=1,drag=null,hover=null,hoverDef=null,last=performance.now(),speed=1,shots=[],fx=[],drops=[],dropClock=35,modalAction=null;
function load(){try{let p=JSON.parse(localStorage.getItem(SAVE)||'{}');return{energy:Number.isFinite(p.energy)?p.energy:0,unlocked:Array.isArray(p.unlocked)?p.unlocked:[1,2,3],dev:false}}catch(e){return{energy:0,unlocked:[1,2,3],dev:false}}}function save(){localStorage.setItem(SAVE,JSON.stringify(profile))}
function unlocked(id){return profile.dev||profile.unlocked.includes(id)}function mobile(){return innerWidth<=900}
function geom(){let r=C.getBoundingClientRect(),tw=Math.min(70,(r.width*.86)/(GW), (r.height*.66)/(GH*.5));tw=Math.max(24,tw);return{tw,th:tw/2,ox:r.width*.5,oy:r.height*.22}}function iso(x,y){let g=geom();return{x:(x-y)*g.tw/2,y:(x+y)*g.th/2}}function center(x,y){let g=geom(),p=iso(x+.5,y+.5);return{x:g.ox+p.x,y:g.oy+p.y}}function tile(px,py){let g=geom(),x=px-g.ox,y=py-g.oy;return{x:Math.floor(y/g.th+x/g.tw),y:Math.floor(y/g.th-x/g.tw)}}
function resize(){let r=C.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);C.width=Math.max(1,r.width*d);C.height=Math.max(1,r.height*d);X.setTransform(d,0,0,d,0,0)}new ResizeObserver(resize).observe(C);
function log(s){let d=document.createElement('div');d.textContent='> '+s;$('log').prepend(d);while($('log').children.length>10)$('log').lastChild.remove()}
function chooseRoute(){let a=ROUTES.map((_,i)=>i).filter(i=>i!==routeIndex);routeIndex=a[Math.floor(Math.random()*a.length)]??0;path=ROUTES[routeIndex];pathSet=new Set(path.map(p=>p.join(',')));$('maptag').textContent='NEO TOKYO // SECTOR '+String(routeIndex+1).padStart(2,'0')}
function reset(){chooseRoute();power=220;core=maxCore=20;coreLevel=1;chapter=1;wave=0;defenders=[];enemies=[];spawnQ=[];running=false;paused=false;ended=false;selected=null;drag=null;hover=null;shots=[];fx=[];drops=[];dropClock=32+Math.random()*30;speed=1;$('log').innerHTML='';closeContext();closeModal();log('Neo Tokyo defense grid online.');sync()}
function valid(x,y,ignore=null){return x>=0&&y>=0&&x<GW&&y<GH&&!pathSet.has(x+','+y)&&!defenders.some(d=>d!==ignore&&d.x===x&&d.y===y)}
function diamond(x,y,fill,stroke,lw=1){let g=geom(),p=iso(x,y);X.beginPath();X.moveTo(g.ox+p.x,g.oy+p.y);X.lineTo(g.ox+p.x+g.tw/2,g.oy+p.y+g.th/2);X.lineTo(g.ox+p.x,g.oy+p.y+g.th);X.lineTo(g.ox+p.x-g.tw/2,g.oy+p.y+g.th/2);X.closePath();X.fillStyle=fill;X.fill();X.strokeStyle=stroke;X.lineWidth=lw;X.stroke()}
function backdrop(r){let horizon=r.height*.39;let grad=X.createLinearGradient(0,0,0,r.height);grad.addColorStop(0,'#020316');grad.addColorStop(.45,'#08132b');grad.addColorStop(1,'#030611');X.fillStyle=grad;X.fillRect(0,0,r.width,r.height);
 // moon + distant megastructures
 X.fillStyle='#27104a';X.beginPath();X.arc(r.width*.78,r.height*.15,Math.min(r.width,r.height)*.075,0,7);X.fill();X.fillStyle='#ff3dc8';X.fillRect(r.width*.775,r.height*.075,2,r.height*.15);
 for(let i=0;i<22;i++){let bw=22+(i*17%48),bh=45+(i*43%150),x=i*r.width/21-bw/2,y=horizon-bh;X.fillStyle=i%5===0?'#0d1738':'#08112a';X.fillRect(x,y,bw,bh);X.fillStyle=i%3?'#21dfff':'#ff39cb';for(let wy=y+9;wy<horizon-5;wy+=12)for(let wx=x+6;wx<x+bw-4;wx+=10)if((wx+wy+i)%4<2)X.fillRect(wx,wy,3,4)}
 // elevated transit and neon conduits wrap behind/around board
 X.fillStyle='#111a32';X.fillRect(0,horizon-5,r.width,10);X.fillStyle='#ff3dc8';X.fillRect(0,horizon-2,r.width,2);
 X.strokeStyle='#153a57';X.lineWidth=3;for(let i=0;i<7;i++){let x=i*r.width/6;X.beginPath();X.moveTo(x,horizon);X.lineTo(x,r.height);X.stroke()}
 // foreground tech decks at edges
 X.fillStyle='#071322';X.fillRect(0,r.height*.83,r.width,r.height*.17);X.strokeStyle='#0b7698';X.lineWidth=1;for(let x=0;x<r.width;x+=42){X.strokeRect(x,r.height*.83,38,18);X.fillStyle=x%84?'#11344b':'#34134a';X.fillRect(x+5,r.height*.85,20,5)}
 // pipes/cables around playable area
 X.strokeStyle='#1fdcff';X.lineWidth=2;X.beginPath();X.moveTo(0,r.height*.73);X.lineTo(r.width*.12,r.height*.73);X.lineTo(r.width*.17,r.height*.78);X.stroke();X.strokeStyle='#ff3dc8';X.beginPath();X.moveTo(r.width,r.height*.69);X.lineTo(r.width*.88,r.height*.69);X.lineTo(r.width*.84,r.height*.75);X.stroke();
}
function rangeRing(d,x=d.x,y=d.y,c='#35efff'){let g=geom(),p=center(x,y);X.strokeStyle=c;X.lineWidth=2;X.globalAlpha=.82;X.beginPath();X.ellipse(p.x,p.y,d.range*g.tw/2,d.range*g.th/2,0,0,7);X.stroke();X.globalAlpha=1}
function draw(){let r=C.getBoundingClientRect(),g=geom();X.clearRect(0,0,r.width,r.height);backdrop(r);for(let s=0;s<GW+GH-1;s++)for(let y=0;y<GH;y++){let x=s-y;if(x<0||x>=GW)continue;let road=pathSet.has(x+','+y),h=hover&&hover.x===x&&hover.y===y&&drag?.type==='char',v=valid(x,y,drag?.moving||null);diamond(x,y,road?((x+y)%2?'#151a40':'#201947'):((x+y)%2?'#07162b':'#081d31'),h?(v?'#4effff':'#ff3e7a'):'#087ca8',h?3:1);if(road){let c=center(x,y);X.fillStyle='#ff42d0';X.fillRect(c.x-3,c.y-3,6,6)}}let ec=center(...path[path.length-1]);X.shadowColor='#2eeaff';X.shadowBlur=16;X.fillStyle='#113b58';X.fillRect(ec.x-15,ec.y-30,30,30);X.fillStyle='#2eeaff';X.fillRect(ec.x-4,ec.y-21,8,15);X.shadowBlur=0;defenders.forEach(drawDef);enemies.forEach(drawEnemy);drawShots();drawFX();drawDrops();if(drag?.type==='char'&&hover){let rr=drag.moving||drag.ch;rangeRing(rr,hover.x,hover.y,valid(hover.x,hover.y,drag.moving||null)?'#35efff':'#ff3e7a')}}
function drawDef(d){let ch=chars[d.cid-1],p=center(d.x,d.y);X.shadowColor=ch.color;X.shadowBlur=12;X.fillStyle=ch.color;X.fillRect(p.x-9,p.y-27,18,20);X.fillStyle='#efffff';X.fillRect(p.x-6,p.y-35,12,9);X.fillStyle='#07101c';X.fillRect(p.x-3,p.y-32,2,2);X.fillRect(p.x+2,p.y-32,2,2);X.fillStyle=ch.color;X.fillRect(p.x+8,p.y-21,11,4);X.shadowBlur=0;if(d===selected){rangeRing(d);let q=center(d.x,d.y);X.shadowColor=ch.color;X.shadowBlur=22;X.strokeStyle='#fff';X.lineWidth=2;X.strokeRect(q.x-15,q.y-40,30,36);X.shadowBlur=0;X.fillStyle='#fff';X.font='8px Consolas';X.fillText('UPGRADE TARGET',q.x-31,q.y-46)}}
function epos(e){let a=path[Math.min(e.i,path.length-1)],b=path[Math.min(e.i+1,path.length-1)]||a,A=center(...a),B=center(...b);return{x:A.x+(B.x-A.x)*e.u,y:A.y+(B.y-A.y)*e.u}}
function drawEnemy(e){let p=epos(e);X.shadowColor='#72ff3d';X.shadowBlur=8;X.fillStyle=e.hit?'#fff':'#63ff52';X.fillRect(p.x-7,p.y-20,14,18);X.fillStyle='#702cff';X.fillRect(p.x-5,p.y-27,10,8);X.shadowBlur=0;X.fillStyle='#170c25';X.fillRect(p.x-10,p.y-34,20,3);X.fillStyle='#ff3e76';X.fillRect(p.x-10,p.y-34,20*e.hp/e.max,3)}
function drawShots(){shots.forEach(s=>{X.strokeStyle=s.color;X.shadowColor=s.color;X.shadowBlur=12;X.lineWidth=s.kind==='laser'?4:2;X.beginPath();X.moveTo(s.a.x,s.a.y-16);X.lineTo(s.b.x,s.b.y-13);X.stroke();if(s.kind==='pulse'){X.fillStyle='#fff';X.fillRect(s.b.x-3,s.b.y-16,6,6)}X.shadowBlur=0})}
function drawFX(){fx.forEach(f=>{X.globalAlpha=Math.max(0,1-f.age/f.ttl);if(f.kind==='boom'){for(let i=0;i<12;i++){let a=i*Math.PI/6,rad=5+f.age*32;X.fillStyle=i%2?'#ff4b2b':'#ffe45b';X.fillRect(f.x+Math.cos(a)*rad-3,f.y+Math.sin(a)*rad-3,6,6)}X.fillStyle='#fff';X.fillRect(f.x-5,f.y-5,10,10)}else if(f.kind==='arc'){X.strokeStyle='#b873ff';X.lineWidth=2;X.beginPath();X.moveTo(f.x-12,f.y);X.lineTo(f.x-4,f.y-8);X.lineTo(f.x+2,f.y+5);X.lineTo(f.x+11,f.y-6);X.stroke()}else{X.fillStyle='#ff9b32';for(let i=0;i<5;i++)X.fillRect(f.x-8+i*4,f.y-4-(i%2)*5,4,8)}});X.globalAlpha=1}
function drawDrops(){drops.forEach(d=>{let p=center(d.x,d.y);X.shadowColor='#ffe65b';X.shadowBlur=14;X.fillStyle='#6b3d21';X.fillRect(p.x-10,p.y-25,20,15);X.fillStyle='#d78b36';X.fillRect(p.x-8,p.y-23,16,4);X.fillStyle='#ffe65b';X.fillRect(p.x-2,p.y-25,4,15);X.shadowBlur=0;X.fillStyle='#fff';X.font='8px Consolas';X.fillText('SUPPLY',p.x-17,p.y-29)})}
function roster(){let host=$('roster'),sig=profile.dev+'|'+profile.energy+'|'+profile.unlocked.join(',')+'|'+selectedCard;if(host.dataset.sig===sig)return;host.dataset.sig=sig;host.innerHTML='';chars.forEach(ch=>{let u=unlocked(ch.id),d=document.createElement('div');d.className='card '+(u?'unlocked':'locked')+(!u&&profile.energy>=ch.unlock?' canunlock':'')+(selectedCard===ch.id?' inspecting':'');d.dataset.id=ch.id;d.innerHTML='<div class="portrait"><img draggable="false" src="assets/character-'+String(ch.id).padStart(2,'0')+'.png" alt="'+ch.name+' portrait"></div><div class="cardname" style="color:'+ch.color+'">'+ch.name+'</div><div class="cardrole">'+(u?ch.role:'LOCKED')+'</div><div class="cardcost">'+(u?ch.cost+' PWR':ch.unlock+' NRG')+'</div>';d.addEventListener('click',()=>selectCard(ch.id));if(u)d.addEventListener('pointerdown',cardPointerDown);else d.addEventListener('dblclick',()=>unlockChar(ch.id));host.appendChild(d)})}
let down=null;
function cardPointerDown(ev){let id=+ev.currentTarget.dataset.id,ch=chars[id-1];down={x:ev.clientX,y:ev.clientY,id,ev};let move=e=>{if(!down)return;if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>8){window.removeEventListener('pointermove',move);down=null;startCharDrag(e,ch)}};let up=e=>{window.removeEventListener('pointermove',move);if(down){selectCard(id);down=null}};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})}
function selectCard(id){selectedCard=id;let ch=chars[id-1];if(!unlocked(id)&&profile.energy>=ch.unlock){showModal('UNLOCK '+ch.name+'?','Spend '+ch.unlock+' ENERGY to permanently unlock '+ch.role+'?','UNLOCK',()=>unlockChar(id),'CANCEL',closeModal)}else{selected=null;closeContext();sync()}}
function unlockChar(id){let ch=chars[id-1];if(unlocked(id)||profile.energy<ch.unlock)return;profile.energy-=ch.unlock;profile.unlocked.push(id);save();closeModal();log(ch.name+' permanently unlocked.');sync()}
function beginGhost(ev,label){$('ghost').style.display='block';$('ghost').innerHTML=label;moveDrag(ev);window.addEventListener('pointermove',moveDrag);window.addEventListener('pointerup',endDrag,{once:true})}
function startCharDrag(ev,ch){if(power<ch.cost){log('Insufficient POWER.');return}drag={type:'char',ch};beginGhost(ev,'<b>'+ch.name+'</b><br>'+ch.role)}
function startUpgradeDrag(ev,ix){if(!selected)return;let ch=chars[selected.cid-1],n=ch.tree[ix];if(selected.branch!==null||power<n[3])return;drag={type:'upgrade',target:selected,ix,node:n};beginGhost(ev,'<b>'+n[0]+'</b><br>'+n[3]+' POWER')}
function moveDrag(ev){if(!drag)return;let sr=stage.getBoundingClientRect(),cr=C.getBoundingClientRect();$('ghost').style.left=(ev.clientX-sr.left+12)+'px';$('ghost').style.top=(ev.clientY-sr.top+12)+'px';hover=tile(ev.clientX-cr.left,ev.clientY-cr.top);hoverDef=defenders.find(d=>d.x===hover.x&&d.y===hover.y)||null}
function endDrag(ev){window.removeEventListener('pointermove',moveDrag);$('ghost').style.display='none';if(!drag)return;let cr=C.getBoundingClientRect(),inside=ev.clientX>=cr.left&&ev.clientX<=cr.right&&ev.clientY>=cr.top&&ev.clientY<=cr.bottom,p=inside?tile(ev.clientX-cr.left,ev.clientY-cr.top):null;if(drag.type==='char'){if(p&&valid(p.x,p.y,drag.moving||null)){if(drag.moving){drag.moving.x=p.x;drag.moving.y=p.y;log('Defender repositioned.')}else{power-=drag.ch.cost;defenders.push(makeDef(drag.ch,p.x,p.y));log(drag.ch.name+' deployed.')}}}else if(hoverDef===drag.target)applyUpgrade(hoverDef,drag.ix);drag=null;hover=null;hoverDef=null;sync()}
function makeDef(ch,x,y){return{cid:ch.id,x,y,level:1,cd:.1,range:ch.range,damage:ch.damage,rate:ch.rate,splash:ch.splash||0,branch:null}}
function applyUpgrade(d,ix){let ch=chars[d.cid-1],n=ch.tree[ix];if(d.branch!==null||power<n[3])return;power-=n[3];d.branch=ix;d.level=2;if(n[2]==='rate')d.rate*=.7;if(n[2]==='damage')d.damage*=n[0].includes('RAIL')||n[0].includes('SINGULAR')?1.6:n[0].includes('ION')?1.45:1.5;if(n[2]==='range')d.range*=n[0]==='CHAIN'?1.2:1.25;if(n[2]==='splash')d.splash*=1.45;log(ch.name+' installed '+n[0]+'.');closeContext();sync()}
function showContext(d){let ch=chars[d.cid-1],p=center(d.x,d.y),el=$('context'),html='<div class="bubble"><div class="ctxhead"><div class="title">'+ch.name+' // '+ch.role+'</div><button class="ctxclose" type="button">×</button></div><div class="ctxstats">LVL '+d.level+' · DMG '+Math.round(d.damage)+' · RNG '+d.range.toFixed(1)+' · RATE '+d.rate.toFixed(2)+'s</div>';if(d.branch===null){html+='<div class="ctxhint">SELECT FIELD UPGRADE</div>';ch.tree.forEach((n,i)=>html+='<button type="button" data-up="'+i+'" '+(power<n[3]?'disabled':'')+'><b>'+n[0]+'</b> — '+n[3]+' PWR<br><small>'+n[1]+'</small></button>')}else html+='<div style="font-size:8px;color:#35ff9b;margin-top:6px">INSTALLED: '+ch.tree[d.branch][0]+'</div>';html+='</div>';el.innerHTML=html;let panelW=Math.min(230,stage.clientWidth-12),left=p.x+24;if(left+panelW>stage.clientWidth-6)left=p.x-panelW-24;el.style.left=Math.max(6,Math.min(stage.clientWidth-panelW-6,left))+'px';el.style.top=Math.max(6,Math.min(stage.clientHeight-205,p.y-95))+'px';el.classList.add('show');el.querySelector('.ctxclose').onclick=e=>{e.stopPropagation();closeContext()};el.querySelectorAll('[data-up]').forEach(b=>{b.onpointerdown=e=>e.stopPropagation();b.onclick=e=>{e.stopPropagation();applyUpgrade(d,+b.dataset.up)}})}
function closeContext(){$('context').classList.remove('show')}
C.addEventListener('pointerdown',ev=>{if(drag)return;let r=C.getBoundingClientRect(),p=tile(ev.clientX-r.left,ev.clientY-r.top),crate=drops.find(a=>a.x===p.x&&a.y===p.y);if(crate){profile.energy+=crate.amount;save();drops.splice(drops.indexOf(crate),1);log('Supply crate +'+crate.amount+' ENERGY.');sync();return}let d=defenders.find(a=>a.x===p.x&&a.y===p.y);if(d&&wave===0&&!running&&!mobile()&&ev.shiftKey){drag={type:'char',ch:chars[d.cid-1],moving:d};selected=d;beginGhost(ev,'<b>REPOSITION</b>');return}selected=d||null;if(d)showContext(d);else closeContext();sync()});
function startWave(){if(running||paused||ended||wave>=8)return;wave++;running=true;for(let i=0;i<5+wave*2+chapter;i++)spawnQ.push(i*.72);log('CH '+chapter+' / WAVE '+wave+' inbound.');sync()}
function spawn(){let hp=40+wave*13+(chapter-1)*30;enemies.push({i:0,u:0,hp,max:hp,v:.52+wave*.025+(chapter-1)*.015,reward:10+wave,hit:0})}
function damage(e,n){e.hp-=n;e.hit=.08;if(e.hp<=0){let i=enemies.indexOf(e);if(i>=0){power+=e.reward;enemies.splice(i,1)}}}
function supply(){let amount=15+5*Math.floor(Math.random()*4),x,y,k=0;do{x=Math.floor(Math.random()*GW);y=Math.floor(Math.random()*GH)}while((pathSet.has(x+','+y)||defenders.some(d=>d.x===x&&d.y===y))&&k++<30);drops.push({x,y,amount,age:0,ttl:12});log('Rare supply crate detected.')}
function fire(d,e){let ch=chars[d.cid-1],a=center(d.x,d.y),b=epos(e);shots.push({a,b,color:ch.color,kind:ch.weapon,life:ch.weapon==='laser'?.15:.09});if(ch.weapon==='explosive')fx.push({x:b.x,y:b.y-10,kind:'boom',age:0,ttl:.38});else if(ch.weapon==='arc')fx.push({x:b.x,y:b.y-12,kind:'arc',age:0,ttl:.22});else fx.push({x:b.x,y:b.y-12,kind:'fire',age:0,ttl:.16})}
function update(dt){shots.forEach(s=>s.life-=dt);shots=shots.filter(s=>s.life>0);fx.forEach(f=>f.age+=dt);fx=fx.filter(f=>f.age<f.ttl);drops.forEach(d=>d.age+=dt);drops=drops.filter(d=>d.age<d.ttl);if(paused||ended)return;if(running){dropClock-=dt;if(dropClock<=0){supply();dropClock=32+Math.random()*34}for(let i=spawnQ.length-1;i>=0;i--){spawnQ[i]-=dt;if(spawnQ[i]<=0){spawn();spawnQ.splice(i,1)}}}for(let i=enemies.length-1;i>=0;i--){let e=enemies[i];e.hit=Math.max(0,e.hit-dt);e.u+=e.v*dt;if(e.u>=1){e.u--;e.i++;if(e.i>=path.length-1){core-=2;enemies.splice(i,1);if(core<=0)lose()}}}let g=geom();for(let d of defenders){d.cd-=dt;if(d.cd>0)continue;let dc=center(d.x,d.y),best=null,prog=-1;for(let e of enemies){let p=epos(e),dist=Math.hypot(p.x-dc.x,(p.y-dc.y)*2)/(g.tw/2),pr=e.i+e.u;if(dist<=d.range&&pr>prog){best=e;prog=pr}}if(best){d.cd=d.rate;fire(d,best);let bp=epos(best);if(d.splash)[...enemies].forEach(e=>{let p=epos(e);if(Math.hypot(p.x-bp.x,(p.y-bp.y)*2)<=d.splash*g.tw/2)damage(e,d.damage)});else damage(best,d.damage)}}if(running&&!spawnQ.length&&!enemies.length){running=false;power+=25+wave*5;log('Wave clear // POWER bonus.');if(wave>=8)chapterClear()}sync()}
function chapterClear(){let reward=250+(core>=maxCore*.75?100:0)+(core===maxCore?100:0);profile.energy+=reward;save();ended=true;showModal('CHAPTER '+chapter+' COMPLETE','+'+reward+' ENERGY banked. Continue to a new Neo Tokyo sector?','NEXT CHAPTER',nextChapter,'REPLAY',reset)}
function nextChapter(){chapter++;chooseRoute();wave=0;ended=false;core=maxCore;dropClock=30+Math.random()*30;closeModal();log('Sector changed // Chapter '+chapter+'.');sync()}
function lose(){ended=true;running=false;showModal('CORE OVERRUN','Banked ENERGY and permanent unlocks are safe.','RETRY',()=>{enemies=[];spawnQ=[];wave=0;core=maxCore;ended=false;running=false;closeModal();sync()},'RESET RUN',reset)}
function coreUpgrade(){let c=80+(coreLevel-1)*45;if(power<c)return;power-=c;coreLevel++;maxCore+=5;core+=5;log('Core upgraded to '+maxCore+' HP.');sync()}
function showModal(t,txt,p,a,s,b){$('modalTitle').textContent=t;$('modalText').innerHTML=txt;$('modalPrimary').textContent=p;$('modalSecondary').textContent=s||'';$('modalSecondary').style.display=s?'inline-block':'none';modalAction=a;$('modalSecondary').onclick=b||closeModal;$('modal').classList.add('show')}function closeModal(){$('modal').classList.remove('show');modalAction=null}
function sync(){$('chapter').textContent=chapter;$('wave').textContent=wave;$('power').textContent=power;$('energy').textContent=profile.energy;$('core').textContent=Math.max(0,core)+'/'+maxCore;$('hostiles').textContent=enemies.length;$('waveBtn').disabled=running||paused||ended;$('pauseBtn').textContent=paused?'RESUME':'PAUSE';$('paused').classList.toggle('show',paused);$('speedBtn').textContent='SPEED ×'+speed;$('speedBtn').classList.toggle('active',speed>1);$('coreLevel').textContent=coreLevel;let cc=80+(coreLevel-1)*45;$('coreCost').textContent=cc;$('coreUpgrade').disabled=power<cc;$('modeLabel').textContent='MODE: '+(profile.dev?'DEV — TEMPORARY ROSTER':'STANDARD');roster();let ch=selected?chars[selected.cid-1]:chars[selectedCard-1],d=selected,uiSig=[selected?defenders.indexOf(selected):-1,selectedCard,power,selected?selected.level:0,selected?selected.branch:'x',profile.dev,profile.energy].join('|');if($('detail').dataset.sig===uiSig)return;$('detail').dataset.sig=uiSig;$('detail').innerHTML='<strong style="color:'+ch.color+'">'+ch.name+' // '+ch.role+'</strong><div class="bars"><div class="metric">DMG<b>'+Math.round(d?d.damage:ch.damage)+'</b></div><div class="metric">RANGE<b>'+(d?d.range:ch.range).toFixed(1)+'</b></div><div class="metric">RATE<b>'+(d?d.rate:ch.rate).toFixed(2)+'s</b></div></div>'+(selected?'<div style="margin-top:4px">DEPLOYED LVL '+selected.level+'</div>':'<div style="margin-top:4px">'+(unlocked(ch.id)?'DRAG CARD TO DEPLOY · '+ch.cost+' POWER':'LOCKED · '+ch.unlock+' ENERGY')+'</div>');let tr=$('tree');tr.innerHTML='';if(selected)ch.tree.forEach((n,i)=>{let u=document.createElement('div');u.className='upgrade '+(selected.branch===i?'installed':selected.branch===null&&power>=n[3]?'available':'');u.innerHTML='<strong>'+n[0]+'</strong><small>'+n[1]+'</small><small class="cost">'+n[3]+' POWER</small>';if(selected.branch===null)u.addEventListener('pointerdown',e=>startUpgradeDrag(e,i));tr.appendChild(u)})}
$('waveBtn').onclick=startWave;$('pauseBtn').onclick=()=>{if(!ended){paused=!paused;sync()}};$('speedBtn').onclick=()=>{speed=speed===3?1:speed+1;sync()};$('resetBtn').onclick=()=>showModal('RESET RUN?','POWER, battlefield and Chapter progress reset. ENERGY/unlocks remain safe.','RESET',reset,'CANCEL',closeModal);$('coreUpgrade').onclick=coreUpgrade;$('modalPrimary').onclick=()=>modalAction&&modalAction();$('devBtn').onclick=()=>{if($('devCode').value.trim().toUpperCase()===DEV){profile.dev=true;save();$('devCode').value='';log('DEV MODE enabled.');sync()}else log('DEV ACCESS denied.')};$('stdBtn').onclick=()=>{profile.dev=false;save();log('STANDARD progression restored.');sync()};
function frame(n){let dt=Math.min((n-last)/1000,.05)*speed;last=n;update(dt);draw();requestAnimationFrame(frame)}reset();requestAnimationFrame(frame);
})();