(()=>{'use strict';
const $=id=>document.getElementById(id),C=$('game'),X=C.getContext('2d'),stage=$('stage'),GW=12,GH=12,SAVE='dead-grid-profile-v3',DEV='NEON8';
const ROUTES=[
[[0,1],[1,1],[2,1],[3,1],[4,1],[5,1],[6,1],[7,1],[8,1],[9,1],[10,1],[11,1]],
[[0,10],[1,10],[2,10],[2,9],[2,8],[2,7],[3,7],[4,7],[5,7],[6,7],[7,7],[7,6],[7,5],[7,4],[8,4],[9,4],[10,4],[11,4]],
[[0,2],[1,2],[2,2],[2,3],[2,4],[3,4],[4,4],[5,4],[5,3],[5,2],[6,2],[7,2],[8,2],[8,3],[8,4],[8,5],[9,5],[10,5],[11,5]],
[[0,8],[1,8],[1,7],[1,6],[2,6],[3,6],[4,6],[4,7],[4,8],[5,8],[6,8],[7,8],[7,7],[7,6],[8,6],[9,6],[9,7],[9,8],[10,8],[11,8]],
[[0,5],[1,5],[1,4],[1,3],[2,3],[3,3],[3,4],[3,5],[3,6],[4,6],[5,6],[5,5],[5,4],[6,4],[7,4],[7,5],[7,6],[8,6],[9,6],[9,5],[9,4],[10,4],[11,4]],
[[0,0],[1,0],[2,0],[3,0],[3,1],[3,2],[3,3],[3,4],[4,4],[5,4],[6,4],[6,5],[6,6],[6,7],[7,7],[8,7],[9,7],[9,8],[9,9],[10,9],[11,9]],
[[0,11],[1,11],[2,11],[3,11],[4,11],[4,10],[4,9],[4,8],[4,7],[5,7],[6,7],[7,7],[7,6],[7,5],[7,4],[7,3],[8,3],[9,3],[10,3],[11,3]],
[[0,3],[1,3],[2,3],[3,3],[3,4],[3,5],[3,6],[3,7],[4,7],[5,7],[6,7],[6,6],[6,5],[6,4],[6,3],[7,3],[8,3],[8,4],[8,5],[8,6],[8,7],[9,7],[10,7],[11,7]],
[[0,9],[1,9],[2,9],[3,9],[3,8],[3,7],[3,6],[4,6],[5,6],[5,5],[5,4],[5,3],[6,3],[7,3],[7,4],[7,5],[7,6],[8,6],[9,6],[9,5],[9,4],[10,4],[11,4]],
[[0,6],[1,6],[2,6],[2,5],[2,4],[2,3],[3,3],[4,3],[5,3],[5,4],[5,5],[5,6],[5,7],[6,7],[7,7],[8,7],[8,6],[8,5],[8,4],[9,4],[10,4],[11,4]],
[[0,1],[1,1],[1,2],[1,3],[1,4],[1,5],[2,5],[3,5],[4,5],[4,4],[4,3],[5,3],[6,3],[7,3],[7,4],[7,5],[7,6],[8,6],[9,6],[10,6],[10,7],[10,8],[11,8]],
[[0,10],[1,10],[1,9],[1,8],[2,8],[3,8],[4,8],[4,9],[5,9],[6,9],[7,9],[7,8],[7,7],[7,6],[6,6],[5,6],[5,5],[5,4],[6,4],[7,4],[8,4],[9,4],[9,3],[10,3],[11,3]]];
const DISTRICTS=[
['SHINJUKU DEAD ZONE','新宿 // 危険'],['HAN RIVER STACK','한강 // 위험'],['AKIHABARA BLACKOUT','秋葉原 // 停電'],['NEON HARBOR','港区 // 警告'],['KOWLOON GHOST STACK','九龍 // 立入禁止'],['SUBLEVEL TRANSIT','地下鉄 // 出口'],['SEOUL INDUSTRIAL RING','산업구역 // 폐쇄'],['SHIBUYA NULL','渋谷 // 電力'],['NIGHT MARKET 09','야시장 // 구역'],['MEGABLOCK K-12','第12区 // 위험'],['RAINLINE DISTRICT','雨線 // 警告'],['VOID TERMINAL','終端 // 폐쇄']];
const PORTRAITS=Array.from({length:8},(_,i)=>{let im=new Image();im.src='assets/character-'+String(i+1).padStart(2,'0')+'.png';return im});
const chars=[
{id:1,name:'CHARACTER 1',role:'Pulse Assault',cost:60,unlock:0,color:'#ff3ec8',range:2.45,damage:9,rate:.38,weapon:'pulse',tree:[['OVERDRIVE','Fire rate +30%','rate',70],['ION ROUNDS','Damage +45%','damage',70]]},
{id:2,name:'CHARACTER 2',role:'Arc Sniper',cost:95,unlock:0,color:'#6dffef',range:3.8,damage:27,rate:1.25,weapon:'laser',tree:[['DEAD EYE','Range +25%','range',80],['RAIL CORE','Damage +60%','damage',80]]},
{id:3,name:'CHARACTER 3',role:'Nova Tech',cost:80,unlock:0,color:'#ff9d31',range:2,damage:18,rate:1.45,splash:1.1,weapon:'explosive',tree:[['WIDE NOVA','Blast radius +45%','splash',75],['HOT CORE','Damage +50%','damage',75]]},
{id:4,name:'CHARACTER 4',role:'Volt Warden',cost:105,unlock:1000,color:'#9b62ff',range:2.7,damage:17,rate:.72,weapon:'arc',tree:[['CHAIN','Range +20%','range',95],['SURGE','Damage +50%','damage',95]]},
{id:5,name:'CHARACTER 5',role:'Photon Monk',cost:115,unlock:2500,color:'#ffe73c',range:2.2,damage:21,rate:.65,weapon:'pulse',tree:[['FOCUS','Range +25%','range',105],['FLARE','Damage +50%','damage',105]]},
{id:6,name:'CHARACTER 6',role:'Crimson Gear',cost:130,unlock:5000,color:'#ff455d',range:2.8,damage:30,rate:1.05,weapon:'explosive',tree:[['TURBO','Fire rate +30%','rate',120],['REDLINE','Damage +50%','damage',120]]},
{id:7,name:'CHARACTER 7',role:'Bio Spark',cost:145,unlock:8500,color:'#38ff7d',range:3,damage:25,rate:.82,weapon:'arc',tree:[['SPORE','Range +25%','range',130],['MUTAGEN','Damage +50%','damage',130]]},
{id:8,name:'CHARACTER 8',role:'Zero Vector',cost:170,unlock:12000,color:'#43a5ff',range:4,damage:42,rate:1.3,weapon:'laser',tree:[['HORIZON','Range +25%','range',150],['SINGULAR','Damage +60%','damage',150]]}];
let profile=load(),path=ROUTES[0],pathSet=new Set(path.map(p=>p.join(','))),routeIndex=0,obstacles=[],power,core,maxCore,coreLevel,chapter,wave,defenders,enemies,spawnQ,running,paused,ended,selected=null,selectedCard=1,drag=null,hover=null,hoverDef=null,last=performance.now(),speed=1,shots=[],fx=[],drops=[],dropClock=35,modalAction=null,autoStart=false,autoDelay=0,chapterCarry=0;
function load(){try{let p=JSON.parse(localStorage.getItem(SAVE)||'{}');return{energy:Number.isFinite(p.energy)?p.energy:0,unlocked:Array.isArray(p.unlocked)?p.unlocked:[1,2,3],dev:false}}catch(e){return{energy:0,unlocked:[1,2,3],dev:false}}}function save(){localStorage.setItem(SAVE,JSON.stringify(profile))}
function unlocked(id){return profile.dev||profile.unlocked.includes(id)}function mobile(){return innerWidth<=900}
function geom(){let r=C.getBoundingClientRect(),tw=Math.min(70,(r.width*.86)/(GW), (r.height*.66)/(GH*.5));tw=Math.max(24,tw);return{tw,th:tw/2,ox:r.width*.5,oy:r.height*.22}}function iso(x,y){let g=geom();return{x:(x-y)*g.tw/2,y:(x+y)*g.th/2}}function center(x,y){let g=geom(),p=iso(x+.5,y+.5);return{x:g.ox+p.x,y:g.oy+p.y}}function tile(px,py){let g=geom(),x=px-g.ox,y=py-g.oy;return{x:Math.floor(y/g.th+x/g.tw),y:Math.floor(y/g.th-x/g.tw)}}
function resize(){let r=C.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);C.width=Math.max(1,r.width*d);C.height=Math.max(1,r.height*d);X.setTransform(d,0,0,d,0,0)}new ResizeObserver(resize).observe(C);
function log(s){let d=document.createElement('div');d.textContent='> '+s;$('log').prepend(d);while($('log').children.length>10)$('log').lastChild.remove()}
function chooseRoute(){let a=ROUTES.map((_,i)=>i).filter(i=>i!==routeIndex);routeIndex=a[Math.floor(Math.random()*a.length)]??0;path=ROUTES[routeIndex];pathSet=new Set(path.map(p=>p.join(',')));buildObstacles();let d=DISTRICTS[routeIndex];$('maptag').textContent=d[0]+' // '+d[1]}
function buildObstacles(){obstacles=[];let seed=(routeIndex+1)*997+(chapter||1)*131,rand=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296),types=[['NEON TERMINAL',20],['BARRICADE',30],['WRECKED K-CAR',45],['GRID TRANSFORMER',60],['FORTIFIED RELAY',75]],count=7+(routeIndex%4),start=path[0],end=path[path.length-1];let candidates=[];for(let y=0;y<GH;y++)for(let x=0;x<GW;x++){let key=x+','+y;if(pathSet.has(key))continue;if((x===start[0]&&y===start[1])||(x===end[0]&&y===end[1]))continue;candidates.push([x,y])}while(obstacles.length<count&&candidates.length){let i=Math.floor(rand()*candidates.length),q=candidates.splice(i,1)[0];if(pathSet.has(q[0]+','+q[1]))continue;let t=types[Math.floor(rand()*types.length)];obstacles.push({x:q[0],y:q[1],name:t[0],cost:t[1],kind:types.indexOf(t)})}obstacles=obstacles.filter(o=>!pathSet.has(o.x+','+o.y))}
function obstructionAt(x,y){return obstacles.find(o=>o.x===x&&o.y===y)}
function reset(){chapter=1;chooseRoute();power=220;core=maxCore=20;coreLevel=1;wave=0;defenders=[];enemies=[];spawnQ=[];running=false;paused=false;ended=false;selected=null;drag=null;hover=null;shots=[];fx=[];drops=[];dropClock=32+Math.random()*30;autoDelay=0;speed=1;$('log').innerHTML='';closeContext();closeModal();log('Neo Tokyo defense grid online.');sync()}
function valid(x,y,ignore=null){return x>=0&&y>=0&&x<GW&&y<GH&&!pathSet.has(x+','+y)&&!obstructionAt(x,y)&&!defenders.some(d=>d!==ignore&&d.x===x&&d.y===y)}
function diamond(x,y,fill,stroke,lw=1){let g=geom(),p=iso(x,y);X.beginPath();X.moveTo(g.ox+p.x,g.oy+p.y);X.lineTo(g.ox+p.x+g.tw/2,g.oy+p.y+g.th/2);X.lineTo(g.ox+p.x,g.oy+p.y+g.th);X.lineTo(g.ox+p.x-g.tw/2,g.oy+p.y+g.th/2);X.closePath();X.fillStyle=fill;X.fill();X.strokeStyle=stroke;X.lineWidth=lw;X.stroke()}
function backdrop(r){let d=routeIndex%6,h=r.height*.39,pals=[['#020316','#08132b','#ff3dc8','#21dfff'],['#061016','#10232b','#33ffbd','#ff3dc8'],['#100417','#25102d','#ff5c35','#b85cff'],['#020b18','#06263a','#2eeaff','#ffe65b'],['#090611','#201127','#ff315f','#6dffef'],['#02050b','#111a25','#9b62ff','#36ff9b']],pal=pals[d],g=X.createLinearGradient(0,0,0,r.height);g.addColorStop(0,pal[0]);g.addColorStop(.48,pal[1]);g.addColorStop(1,'#02040b');X.fillStyle=g;X.fillRect(0,0,r.width,r.height);
X.globalAlpha=.9;X.fillStyle=pal[2];if(d===0||d===4){X.beginPath();X.arc(r.width*.78,r.height*.14,Math.min(r.width,r.height)*.065,0,7);X.fill()}else if(d===3){X.fillRect(r.width*.08,r.height*.12,r.width*.16,3);X.fillRect(r.width*.12,r.height*.09,3,r.height*.13)}X.globalAlpha=1;
for(let i=0;i<26;i++){let bw=18+(i*23%54),bh=38+(i*47%175),x=i*r.width/25-bw/2,y=h-bh;X.fillStyle=i%4===0?'#101a35':'#071024';X.fillRect(x,y,bw,bh);X.fillStyle=i%3?pal[3]:pal[2];for(let wy=y+8;wy<h-5;wy+=11)for(let wx=x+5;wx<x+bw-4;wx+=9)if((wx+wy+i+routeIndex)%5<2)X.fillRect(wx,wy,3,3)}
X.fillStyle='#0b1325';X.fillRect(0,h-4,r.width,12);X.fillStyle=pal[2];X.fillRect(0,h,r.width,2);X.strokeStyle='#173a54';X.lineWidth=3;for(let i=0;i<8;i++){let x=i*r.width/7;X.beginPath();X.moveTo(x,h);X.lineTo(x,r.height);X.stroke()}
// vertical neon signage and layered foreground architecture
X.font='bold 13px sans-serif';let signs=d%2?['危険','폐쇄','電力']:['警告','구역','出口'];signs.forEach((t,i)=>{let x=i===1?r.width-38:12+i*34,y=r.height*(.22+i*.13);X.fillStyle='#050816';X.fillRect(x-5,y-18,28,58);X.strokeStyle=i%2?pal[2]:pal[3];X.strokeRect(x-5,y-18,28,58);X.fillStyle=i%2?pal[2]:pal[3];for(let k=0;k<t.length;k++)X.fillText(t[k],x,y+k*15)});
X.fillStyle='#06101d';X.fillRect(0,r.height*.84,r.width,r.height*.16);for(let x=0;x<r.width;x+=48){X.fillStyle=x%96?'#0b2435':'#24112f';X.fillRect(x,r.height*.84,43,20);X.fillStyle=pal[3];X.fillRect(x+5,r.height*.865,23,3)}X.strokeStyle=pal[3];X.lineWidth=2;X.beginPath();X.moveTo(0,r.height*.74);X.lineTo(r.width*.13,r.height*.74);X.lineTo(r.width*.18,r.height*.79);X.stroke();X.strokeStyle=pal[2];X.beginPath();X.moveTo(r.width,r.height*.70);X.lineTo(r.width*.87,r.height*.70);X.lineTo(r.width*.82,r.height*.77);X.stroke()}
function rangeRing(d,x=d.x,y=d.y,c='#35efff'){let g=geom(),p=center(x,y);X.strokeStyle=c;X.lineWidth=2;X.globalAlpha=.82;X.beginPath();X.ellipse(p.x,p.y,d.range*g.tw/2,d.range*g.th/2,0,0,7);X.stroke();X.globalAlpha=1}
function drawObstacle(o){let p=center(o.x,o.y),g=geom(),h=13+o.kind*3,baseY=p.y+g.th*.12,w=g.tw*.42;X.fillStyle='rgba(0,0,0,.55)';X.beginPath();X.ellipse(p.x,baseY,w*.55,g.th*.20,0,0,Math.PI*2);X.fill();X.shadowColor=o.kind%2?'#ff3dc8':'#2eeaff';X.shadowBlur=8;X.fillStyle=o.kind===2?'#39141e':'#101c2d';X.fillRect(p.x-w/2,baseY-h,w,h);X.fillStyle=o.kind%2?'#ff3dc8':'#2eeaff';X.fillRect(p.x-w*.34,baseY-h+4,w*.68,3);X.fillStyle='#050914';X.beginPath();X.moveTo(p.x-w/2,baseY);X.lineTo(p.x,baseY+g.th*.16);X.lineTo(p.x+w/2,baseY);X.lineTo(p.x,baseY-g.th*.08);X.closePath();X.fill();if(o.kind>=3){X.fillStyle=o.kind%2?'#ff3dc8':'#2eeaff';X.fillRect(p.x-2,baseY-h-9,4,10);X.fillRect(p.x-8,baseY-h-9,16,3)}X.shadowBlur=0}
function draw(){let r=C.getBoundingClientRect(),g=geom();X.clearRect(0,0,r.width,r.height);backdrop(r);for(let s=0;s<GW+GH-1;s++)for(let y=0;y<GH;y++){let x=s-y;if(x<0||x>=GW)continue;let road=pathSet.has(x+','+y),h=hover&&hover.x===x&&hover.y===y&&drag?.type==='char',v=valid(x,y,drag?.moving||null);diamond(x,y,road?((x+y)%2?'#151a40':'#201947'):((x+y)%2?'#07162b':'#081d31'),h?(v?'#4effff':'#ff3e7a'):'#087ca8',h?3:1);let c=center(x,y);X.strokeStyle='#03101a';X.beginPath();X.moveTo(c.x-g.tw/2,c.y);X.lineTo(c.x,c.y+g.th/2+4);X.lineTo(c.x+g.tw/2,c.y);X.stroke();if(road){X.fillStyle='#ff42d0';X.fillRect(c.x-3,c.y-3,6,6)}}obstacles.forEach(drawObstacle);let ec=center(...path[path.length-1]);X.shadowColor='#2eeaff';X.shadowBlur=16;X.fillStyle='#113b58';X.fillRect(ec.x-15,ec.y-30,30,30);X.fillStyle='#2eeaff';X.fillRect(ec.x-4,ec.y-21,8,15);X.shadowBlur=0;defenders.forEach(drawDef);enemies.forEach(drawEnemy);drawShots();drawFX();drawDrops();if(drag?.type==='char'&&hover){let rr=drag.moving||drag.ch;rangeRing(rr,hover.x,hover.y,valid(hover.x,hover.y,drag.moving||null)?'#35efff':'#ff3e7a')}}
function drawDef(d){let ch=chars[d.cid-1],p=center(d.x,d.y),g=geom(),sc=Math.max(1,Math.round(g.tw/34)),pal=[['#211638','#f1b08f','#151226','#ff3ec8','#2eeaff'],['#173744','#e0a58b','#cfefff','#6dffef','#9b62ff'],['#442315','#efad7f','#4b1d12','#ff9d31','#ffe65b'],['#241447','#dca38c','#32185a','#9b62ff','#2eeaff'],['#4b4210','#eab58b','#efe8b4','#ffe73c','#ff3ec8'],['#4b111b','#e0a080','#2a0b10','#ff455d','#ff9d31'],['#123c24','#d8a17e','#142c1c','#38ff7d','#2eeaff'],['#112d4d','#dba58b','#0d1d38','#43a5ff','#9b62ff']][d.cid-1],px=(x,y,w,h,c)=>{X.fillStyle=c;X.fillRect(Math.round(p.x+(x-8)*sc),Math.round(p.y-(18-y)*sc),w*sc,h*sc)};X.save();X.shadowColor=ch.color;X.shadowBlur=10;px(4,2,8,3,pal[0]);px(3,4,10,5,pal[0]);px(4,6,8,5,pal[1]);px(5,7,6,1,'#101018');px(3,11,10,5,pal[2]);px(1,12,3,7,pal[3]);px(12,12,3,7,pal[4]);px(4,16,4,7,pal[2]);px(9,16,4,7,pal[2]);px(3,22,5,2,'#05070c');px(9,22,5,2,'#05070c');if(d.cid===2||d.cid===8){px(14,9,2,10,pal[4]);px(16,7,1,14,'#dffcff')}if(d.cid===3||d.cid===6){px(13,12,4,4,pal[3]);px(16,13,3,2,'#ffe65b')}if(d.cid===4||d.cid===7){px(0,10,2,9,pal[4]);px(-1,9,4,2,'#fff')}X.shadowBlur=0;X.restore();if(d.stun>0){X.strokeStyle='#ffe65b';X.lineWidth=2;X.beginPath();X.arc(p.x,p.y-22*sc,7*sc,0,Math.PI*1.5);X.stroke();X.fillStyle='#ffe65b';X.font='bold '+Math.max(7,7*sc)+'px Consolas';X.fillText('STUN',p.x-9*sc,p.y-27*sc)}if(d===selected){rangeRing(d);X.shadowColor=ch.color;X.shadowBlur=18;X.strokeStyle='#fff';X.strokeRect(p.x-10*sc,p.y-25*sc,20*sc,28*sc);X.shadowBlur=0;X.fillStyle='#fff';X.font='8px Consolas';X.fillText('UPGRADE TARGET',p.x-31,p.y-31*sc)}}
function epos(e){let a=path[Math.min(e.i,path.length-1)],b=path[Math.min(e.i+1,path.length-1)]||a,A=center(...a),B=center(...b);return{x:A.x+(B.x-A.x)*e.u,y:A.y+(B.y-A.y)*e.u}}
function drawEnemy(e){let p=epos(e),g=geom(),sc=Math.max(1,g.tw/42),c=e.color||'#7cff72';X.save();X.shadowColor=c;X.shadowBlur=e.type==='bomber'?13:6;X.fillStyle='#142219';X.fillRect(p.x-5*sc,p.y-17*sc,10*sc,10*sc);X.fillStyle=c;X.fillRect(p.x-4*sc,p.y-15*sc,8*sc,5*sc);X.fillStyle='#05070a';X.fillRect(p.x-3*sc,p.y-14*sc,2*sc,2*sc);X.fillRect(p.x+2*sc,p.y-14*sc,2*sc,2*sc);X.fillStyle=e.type==='brute'?'#4d2630':'#203528';X.fillRect(p.x-6*sc,p.y-7*sc,12*sc,(e.type==='brute'?11:9)*sc);X.fillRect(p.x-8*sc,p.y-6*sc,3*sc,8*sc);X.fillRect(p.x+5*sc,p.y-6*sc,3*sc,8*sc);X.fillRect(p.x-5*sc,p.y+2*sc,4*sc,7*sc);X.fillRect(p.x+1*sc,p.y+2*sc,4*sc,7*sc);if(e.type==='sprinter'){X.fillStyle='#ffe65b';X.fillRect(p.x-8*sc,p.y+9*sc,6*sc,2*sc);X.fillRect(p.x+2*sc,p.y+9*sc,6*sc,2*sc)}if(e.type==='bomber'){X.fillStyle='#ff3ec8';X.fillRect(p.x-4*sc,p.y-5*sc,8*sc,6*sc);X.fillStyle='#fff';X.fillRect(p.x-1*sc,p.y-3*sc,2*sc,2*sc)}if(e.type==='disruptor'){X.strokeStyle='#9b62ff';X.lineWidth=2;X.strokeRect(p.x-7*sc,p.y-9*sc,14*sc,13*sc)}X.shadowBlur=0;X.fillStyle='#03050a';X.fillRect(p.x-10,p.y+11,20,3);X.fillStyle=e.hit?'#fff':c;X.fillRect(p.x-10,p.y+11,20*Math.max(0,e.hp/e.max),3);X.restore()}
function drawShots(){shots.forEach(s=>{X.strokeStyle=s.color;X.shadowColor=s.color;X.shadowBlur=12;X.lineWidth=s.kind==='laser'?4:2;X.beginPath();X.moveTo(s.a.x,s.a.y-16);X.lineTo(s.b.x,s.b.y-13);X.stroke();if(s.kind==='pulse'){X.fillStyle='#fff';X.fillRect(s.b.x-3,s.b.y-16,6,6)}X.shadowBlur=0})}
function drawFX(){fx.forEach(f=>{X.globalAlpha=Math.max(0,1-f.age/f.ttl);if(f.kind==='boom'){for(let i=0;i<12;i++){let a=i*Math.PI/6,rad=5+f.age*32;X.fillStyle=i%2?'#ff4b2b':'#ffe45b';X.fillRect(f.x+Math.cos(a)*rad-3,f.y+Math.sin(a)*rad-3,6,6)}X.fillStyle='#fff';X.fillRect(f.x-5,f.y-5,10,10)}else if(f.kind==='arc'){X.strokeStyle='#b873ff';X.lineWidth=2;X.beginPath();X.moveTo(f.x-12,f.y);X.lineTo(f.x-4,f.y-8);X.lineTo(f.x+2,f.y+5);X.lineTo(f.x+11,f.y-6);X.stroke()}else{X.fillStyle='#ff9b32';for(let i=0;i<5;i++)X.fillRect(f.x-8+i*4,f.y-4-(i%2)*5,4,8)}});X.globalAlpha=1}
function drawDrops(){drops.forEach(d=>{let p=center(d.x,d.y);X.shadowColor='#ffe65b';X.shadowBlur=14;X.fillStyle='#6b3d21';X.fillRect(p.x-10,p.y-25,20,15);X.fillStyle='#d78b36';X.fillRect(p.x-8,p.y-23,16,4);X.fillStyle='#ffe65b';X.fillRect(p.x-2,p.y-25,4,15);X.shadowBlur=0;X.fillStyle='#fff';X.font='8px Consolas';X.fillText('SUPPLY',p.x-17,p.y-29)})}
function roster(){let host=$('roster'),sig=profile.dev+'|'+profile.energy+'|'+profile.unlocked.join(',')+'|'+selectedCard;if(host.dataset.sig===sig)return;host.dataset.sig=sig;host.innerHTML='';chars.forEach(ch=>{let u=unlocked(ch.id),d=document.createElement('div');d.className='card '+(u?'unlocked':'locked')+(!u&&profile.energy>=ch.unlock?' canunlock':'')+(selectedCard===ch.id?' inspecting':'');d.dataset.id=ch.id;d.innerHTML='<div class="portrait"><img draggable="false" src="assets/character-'+String(ch.id).padStart(2,'0')+'.png" alt="'+ch.name+' portrait"></div><div class="cardname" style="color:'+ch.color+'">'+ch.name+'</div><div class="cardrole">'+(u?ch.role:'LOCKED')+'</div><div class="cardcost">'+(u?ch.cost+' PWR':ch.unlock+' NRG')+'</div>';d.addEventListener('click',()=>selectCard(ch.id));if(u)d.addEventListener('pointerdown',cardPointerDown);else d.addEventListener('dblclick',()=>unlockChar(ch.id));host.appendChild(d)})}
let down=null;
function cardPointerDown(ev){let id=+ev.currentTarget.dataset.id,ch=chars[id-1];down={x:ev.clientX,y:ev.clientY,id,ev};let move=e=>{if(!down)return;if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>8){window.removeEventListener('pointermove',move);down=null;startCharDrag(e,ch)}};let up=e=>{window.removeEventListener('pointermove',move);if(down){selectCard(id);down=null}};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})}
function selectCard(id){selectedCard=id;let ch=chars[id-1];if(!unlocked(id)&&profile.energy>=ch.unlock){showModal('UNLOCK '+ch.name+'?','Spend '+ch.unlock+' ENERGY to permanently unlock '+ch.role+'?','UNLOCK',()=>unlockChar(id),'CANCEL',closeModal)}else{selected=null;closeContext();sync()}}
function unlockChar(id){let ch=chars[id-1];if(unlocked(id)||profile.energy<ch.unlock)return;profile.energy-=ch.unlock;profile.unlocked.push(id);save();closeModal();log(ch.name+' permanently unlocked.');sync()}
function beginGhost(ev,label){$('ghost').style.display='block';$('ghost').innerHTML=label;moveDrag(ev);window.addEventListener('pointermove',moveDrag);window.addEventListener('pointerup',endDrag,{once:true})}
function startCharDrag(ev,ch){if(power<ch.cost){log('Insufficient POWER.');return}drag={type:'char',ch};beginGhost(ev,'<b>'+ch.name+'</b><br>'+ch.role)}
function startUpgradeDrag(ev,ix){if(!selected)return;let ch=chars[selected.cid-1],n=ch.tree[ix];if(selected.branch!==null||power<n[3])return;drag={type:'upgrade',target:selected,ix,node:n};beginGhost(ev,'<b>'+n[0]+'</b><br>'+n[3]+' POWER')}
function moveDrag(ev){if(!drag)return;let sr=stage.getBoundingClientRect(),cr=C.getBoundingClientRect();$('ghost').style.left=(ev.clientX-sr.left+12)+'px';$('ghost').style.top=(ev.clientY-sr.top+12)+'px';hover=tile(ev.clientX-cr.left,ev.clientY-cr.top);hoverDef=defenders.find(d=>d.x===hover.x&&d.y===hover.y)||null}
function endDrag(ev){window.removeEventListener('pointermove',moveDrag);$('ghost').style.display='none';if(!drag)return;let cr=C.getBoundingClientRect(),inside=ev.clientX>=cr.left&&ev.clientX<=cr.right&&ev.clientY>=cr.top&&ev.clientY<=cr.bottom,p=inside?tile(ev.clientX-cr.left,ev.clientY-cr.top):null;if(drag.type==='char'){if(p&&valid(p.x,p.y,drag.moving||null)){if(drag.moving){drag.moving.x=p.x;drag.moving.y=p.y;log('Defender repositioned.')}else{power-=drag.ch.cost;defenders.push(makeDef(drag.ch,p.x,p.y));log(drag.ch.name+' deployed.')}}}else if(hoverDef===drag.target)applyUpgrade(hoverDef,drag.ix);drag=null;hover=null;hoverDef=null;sync()}
function makeDef(ch,x,y){return{cid:ch.id,x,y,level:1,cd:.1,range:ch.range,damage:ch.damage,rate:ch.rate,splash:ch.splash||0,branch:null}}
function applyUpgrade(d,ix){let ch=chars[d.cid-1],n=ch.tree[ix];if(d.branch!==null||power<n[3])return;power-=n[3];d.branch=ix;d.level=2;if(n[2]==='rate')d.rate*=.7;if(n[2]==='damage')d.damage*=n[0].includes('RAIL')||n[0].includes('SINGULAR')?1.6:n[0].includes('ION')?1.45:1.5;if(n[2]==='range')d.range*=n[0]==='CHAIN'?1.2:1.25;if(n[2]==='splash')d.splash*=1.45;log(ch.name+' installed '+n[0]+'.');closeContext();sync()}
function showContext(d){let ch=chars[d.cid-1],p=center(d.x,d.y),el=$('context'),html='<div class="bubble"><div class="ctxhead"><div class="title">'+ch.name+' // '+ch.role+'</div><button class="ctxclose" type="button">×</button></div><div class="ctxstats">LVL '+d.level+' · DMG '+Math.round(d.damage)+' · RNG '+d.range.toFixed(1)+' · RATE '+d.rate.toFixed(2)+'s</div>';if(d.branch===null){html+='<div class="ctxhint">SELECT FIELD UPGRADE</div>';ch.tree.forEach((n,i)=>html+='<button type="button" data-up="'+i+'" '+(power<n[3]?'disabled':'')+'><b>'+n[0]+'</b> — '+n[3]+' PWR<br><small>'+n[1]+'</small></button>')}else html+='<div style="font-size:8px;color:#35ff9b;margin-top:6px">INSTALLED: '+ch.tree[d.branch][0]+'</div>';html+='</div>';el.innerHTML=html;let panelW=Math.min(230,stage.clientWidth-12),left=p.x+24;if(left+panelW>stage.clientWidth-6)left=p.x-panelW-24;el.style.left=Math.max(6,Math.min(stage.clientWidth-panelW-6,left))+'px';el.style.top=Math.max(6,Math.min(stage.clientHeight-205,p.y-95))+'px';el.classList.add('show');el.querySelector('.ctxclose').onclick=e=>{e.stopPropagation();closeContext()};el.querySelectorAll('[data-up]').forEach(b=>{b.onpointerdown=e=>e.stopPropagation();b.onclick=e=>{e.stopPropagation();applyUpgrade(d,+b.dataset.up)}})}
function showObstruction(o){let p=center(o.x,o.y),el=$('context'),can=profile.energy>=o.cost;el.innerHTML='<div class="bubble"><div class="ctxhead"><div class="title">GRID OBSTRUCTION</div><button class="ctxclose" type="button">×</button></div><div class="ctxstats">'+o.name+' · BLOCKS DEPLOYMENT</div><div class="ctxhint">CLEARING OPENS THIS TILE FOR THE CURRENT RUN</div><button type="button" id="clearObs" '+(can?'':'disabled')+'><b>DISMANTLE</b> — '+o.cost+' ENERGY</button></div>';let panelW=Math.min(230,stage.clientWidth-12),left=p.x+24;if(left+panelW>stage.clientWidth-6)left=p.x-panelW-24;el.style.left=Math.max(6,Math.min(stage.clientWidth-panelW-6,left))+'px';el.style.top=Math.max(6,Math.min(stage.clientHeight-160,p.y-75))+'px';el.classList.add('show');el.querySelector('.ctxclose').onclick=e=>{e.stopPropagation();closeContext()};let b=el.querySelector('#clearObs');b.onclick=e=>{e.stopPropagation();if(profile.energy<o.cost)return;profile.energy-=o.cost;save();obstacles.splice(obstacles.indexOf(o),1);fx.push({x:p.x,y:p.y-8,kind:'boom',age:0,ttl:.5});log(o.name+' dismantled // -'+o.cost+' ENERGY.');closeContext();sync()}}
function closeContext(){$('context').classList.remove('show')}
C.addEventListener('pointerdown',ev=>{if(drag)return;let r=C.getBoundingClientRect(),p=tile(ev.clientX-r.left,ev.clientY-r.top),crate=drops.find(a=>a.x===p.x&&a.y===p.y);if(crate){profile.energy+=crate.amount;save();drops.splice(drops.indexOf(crate),1);log('Supply crate +'+crate.amount+' ENERGY.');sync();return}let o=obstructionAt(p.x,p.y);if(o){selected=null;showObstruction(o);sync();return}let d=defenders.find(a=>a.x===p.x&&a.y===p.y);if(d&&wave===0&&!running&&!mobile()&&ev.shiftKey){drag={type:'char',ch:chars[d.cid-1],moving:d};selected=d;beginGhost(ev,'<b>REPOSITION</b>');return}selected=d||null;if(d)showContext(d);else closeContext();sync()});
function waveCount(){return 5+wave*2+(chapter-1)*2+Math.floor((chapter-1)/2)*2}
function startWave(){if(running||paused||ended||wave>=8)return;wave++;running=true;autoDelay=0;let count=waveCount(),gap=Math.max(.34,.76-chapter*.018-wave*.012);for(let i=0;i<count;i++)spawnQ.push(i*gap);log('CH '+chapter+' / WAVE '+wave+' // '+count+' hostiles inbound.');sync()}
function zombieType(){let r=Math.random();if(chapter===1){if(wave>=7&&r<.08)return'brute';if(wave>=4&&r<(wave>=7?.24:.12))return'sprinter';return'shambler'}if(chapter===2){if(wave>=7&&r<.05)return'disruptor';if(wave>=4&&r<.18)return'brute';if(wave>=2&&r<.42)return'sprinter';return'shambler'}if(chapter===3){if(wave>=7&&r<.06)return'bomber';if(wave>=4&&r<.16)return'disruptor';if(wave>=3&&r<.32)return'brute';if(r<.55)return'sprinter';return'shambler'}let bomber=Math.min(.16,.05+(chapter-4)*.015+(wave>=6?.03:0)),disrupt=Math.min(.22,.10+(chapter-4)*.015+(wave>=4?.03:0)),brute=Math.min(.28,.16+(chapter-4)*.012),sprinter=Math.min(.34,.22+(chapter-4)*.01);if(wave>=3&&r<bomber)return'bomber';r-=bomber;if(wave>=2&&r<disrupt)return'disruptor';r-=disrupt;if(r<brute)return'brute';r-=brute;if(r<sprinter)return'sprinter';return'shambler'}
function spawn(){let base=40+wave*14+(chapter-1)*32,type=zombieType(),m={shambler:[1,1,'#7cff72'],sprinter:[.68,1.7,'#ffe65b'],brute:[2.15,.62,'#ff6b4a'],bomber:[.92,.92,'#ff3ec8'],disruptor:[1.25,.82,'#9b62ff']}[type],hp=base*m[0];enemies.push({i:0,u:0,hp,max:hp,v:(.52+wave*.025+(chapter-1)*.016)*m[1],reward:Math.round((10+wave)*m[0]),hit:0,type,color:m[2],pulse:2.5+Math.random()*2})}
function stunNearby(e,secs=2.2,fry=false){let p=epos(e),g=geom();defenders.forEach(d=>{let q=center(d.x,d.y),dist=Math.hypot(q.x-p.x,(q.y-p.y)*2)/(g.tw/2);if(dist<=2.25){d.stun=Math.max(d.stun||0,secs);if(fry&&d.branch!==null&&Math.random()<.35){let ch=chars[d.cid-1];d.branch=null;d.level=1;d.range=ch.range;d.damage=ch.damage;d.rate=ch.rate;d.splash=ch.splash||0;log(ch.name+' upgrade fried // reinstall required.')}}});fx.push({x:p.x,y:p.y-10,kind:'arc',age:0,ttl:.45})}
function damage(e,n){e.hp-=n;e.hit=.08;if(e.hp<=0){let i=enemies.indexOf(e);if(i>=0){if(e.type==='bomber')stunNearby(e,2.8,true);power+=e.reward;enemies.splice(i,1)}}}
function supply(){let amount=15+5*Math.floor(Math.random()*4),x,y,k=0;do{x=Math.floor(Math.random()*GW);y=Math.floor(Math.random()*GH)}while((pathSet.has(x+','+y)||obstructionAt(x,y)||defenders.some(d=>d.x===x&&d.y===y))&&k++<30);drops.push({x,y,amount,age:0,ttl:12});log('Rare supply crate detected.')}
function fire(d,e){let ch=chars[d.cid-1],a=center(d.x,d.y),b=epos(e);shots.push({a,b,color:ch.color,kind:ch.weapon,life:ch.weapon==='laser'?.15:.09});if(ch.weapon==='explosive')fx.push({x:b.x,y:b.y-10,kind:'boom',age:0,ttl:.38});else if(ch.weapon==='arc')fx.push({x:b.x,y:b.y-12,kind:'arc',age:0,ttl:.22});else fx.push({x:b.x,y:b.y-12,kind:'fire',age:0,ttl:.16})}
function update(dt){shots.forEach(s=>s.life-=dt);shots=shots.filter(s=>s.life>0);fx.forEach(f=>f.age+=dt);fx=fx.filter(f=>f.age<f.ttl);drops.forEach(d=>d.age+=dt);drops=drops.filter(d=>d.age<d.ttl);if(paused||ended)return;if(running){dropClock-=dt;if(dropClock<=0){supply();dropClock=32+Math.random()*34}for(let i=spawnQ.length-1;i>=0;i--){spawnQ[i]-=dt;if(spawnQ[i]<=0){spawn();spawnQ.splice(i,1)}}}for(let i=enemies.length-1;i>=0;i--){let e=enemies[i];e.hit=Math.max(0,e.hit-dt);if(e.type==='disruptor'){e.pulse-=dt;if(e.pulse<=0){stunNearby(e,1.6,false);e.pulse=3.4}}e.u+=e.v*dt;if(e.u>=1){e.u--;e.i++;if(e.i>=path.length-1){core-=2;enemies.splice(i,1);if(core<=0)lose()}}}let g=geom();for(let d of defenders){d.stun=Math.max(0,(d.stun||0)-dt);if(d.stun>0)continue;d.cd-=dt;if(d.cd>0)continue;let dc=center(d.x,d.y),best=null,prog=-1;for(let e of enemies){let p=epos(e),dist=Math.hypot(p.x-dc.x,(p.y-dc.y)*2)/(g.tw/2),pr=e.i+e.u;if(dist<=d.range&&pr>prog){best=e;prog=pr}}if(best){d.cd=d.rate;fire(d,best);let bp=epos(best);if(d.splash)[...enemies].forEach(e=>{let p=epos(e);if(Math.hypot(p.x-bp.x,(p.y-bp.y)*2)<=d.splash*g.tw/2)damage(e,d.damage)});else damage(best,d.damage)}}if(running&&!spawnQ.length&&!enemies.length){running=false;power+=25+wave*5;log('Wave clear // POWER bonus.');if(wave>=8)chapterClear();else if(autoStart)autoDelay=1.5}if(autoStart&&!running&&!paused&&!ended&&wave<8&&autoDelay>0){autoDelay-=dt;if(autoDelay<=0)startWave()}sync()}
function chapterClear(){let reward=250+(core>=maxCore*.75?100:0)+(core===maxCore?100:0);chapterCarry=Math.floor(power*.45);let purged=power-chapterCarry;profile.energy+=reward;save();defenders=[];selected=null;closeContext();power=chapterCarry;ended=true;showModal('CHAPTER '+chapter+' COMPLETE','+'+reward+' ENERGY banked.<br><br>DEFENDERS RECALLED // '+chapterCarry+' POWER retained (45%).<br>'+purged+' POWER purged.','NEXT CHAPTER',nextChapter,'REPLAY',reset)}
function nextChapter(){chapter++;chooseRoute();wave=0;ended=false;defenders=[];selected=null;core=maxCore;dropClock=30+Math.random()*30;autoDelay=autoStart?1.5:0;closeModal();log('Sector changed // Chapter '+chapter+' // '+power+' POWER carried forward.');sync()}
function lose(){ended=true;running=false;showModal('CORE OVERRUN','Banked ENERGY and permanent unlocks are safe.','RETRY',()=>{enemies=[];spawnQ=[];wave=0;core=maxCore;ended=false;running=false;closeModal();sync()},'RESET RUN',reset)}
function coreUpgrade(){let c=80+(coreLevel-1)*45;if(power<c)return;power-=c;coreLevel++;maxCore+=5;core+=5;log('Core upgraded to '+maxCore+' HP.');sync()}
function showModal(t,txt,p,a,s,b){$('modalTitle').textContent=t;$('modalText').innerHTML=txt;$('modalPrimary').textContent=p;$('modalSecondary').textContent=s||'';$('modalSecondary').style.display=s?'inline-block':'none';modalAction=a;$('modalSecondary').onclick=b||closeModal;$('modal').classList.add('show')}function closeModal(){$('modal').classList.remove('show');modalAction=null}
function sync(){$('chapter').textContent=chapter;$('wave').textContent=wave;$('power').textContent=power;$('energy').textContent=profile.energy;$('core').textContent=Math.max(0,core)+'/'+maxCore;$('hostiles').textContent=enemies.length;$('waveBtn').disabled=running||paused||ended;$('autoBtn').textContent=autoStart?'AUTO ON':'AUTO';$('autoBtn').classList.toggle('active',autoStart);$('pauseBtn').textContent=paused?'RESUME':'PAUSE';$('paused').classList.toggle('show',paused);$('speedBtn').textContent='SPEED ×'+speed;$('speedBtn').classList.toggle('active',speed>1);$('coreLevel').textContent=coreLevel;let cc=80+(coreLevel-1)*45;$('coreCost').textContent=cc;$('coreUpgrade').disabled=power<cc;$('modeLabel').textContent='MODE: '+(profile.dev?'DEV — TEMPORARY ROSTER':'STANDARD');$('devToggle').textContent=profile.dev?'DEV: ON':'DEV';$('devToggle').classList.toggle('active',profile.dev);roster();let ch=selected?chars[selected.cid-1]:chars[selectedCard-1],d=selected,uiSig=[selected?defenders.indexOf(selected):-1,selectedCard,power,selected?selected.level:0,selected?selected.branch:'x',profile.dev,profile.energy].join('|');if($('detail').dataset.sig===uiSig)return;$('detail').dataset.sig=uiSig;$('detail').innerHTML='<strong style="color:'+ch.color+'">'+ch.name+' // '+ch.role+'</strong><div class="bars"><div class="metric">DMG<b>'+Math.round(d?d.damage:ch.damage)+'</b></div><div class="metric">RANGE<b>'+(d?d.range:ch.range).toFixed(1)+'</b></div><div class="metric">RATE<b>'+(d?d.rate:ch.rate).toFixed(2)+'s</b></div></div>'+(selected?'<div style="margin-top:4px">DEPLOYED LVL '+selected.level+'</div>':'<div style="margin-top:4px">'+(unlocked(ch.id)?'DRAG CARD TO DEPLOY · '+ch.cost+' POWER':'LOCKED · '+ch.unlock+' ENERGY')+'</div>');let tr=$('tree');tr.innerHTML='';if(selected)ch.tree.forEach((n,i)=>{let u=document.createElement('div');u.className='upgrade '+(selected.branch===i?'installed':selected.branch===null&&power>=n[3]?'available':'');u.innerHTML='<strong>'+n[0]+'</strong><small>'+n[1]+'</small><small class="cost">'+n[3]+' POWER</small>';if(selected.branch===null)u.addEventListener('pointerdown',e=>startUpgradeDrag(e,i));tr.appendChild(u)})}
$('waveBtn').onclick=startWave;$('autoBtn').onclick=()=>{autoStart=!autoStart;autoDelay=autoStart&&!running&&!ended&&wave<8?1.2:0;log('AUTO START '+(autoStart?'enabled.':'disabled.'));sync()};$('pauseBtn').onclick=()=>{if(!ended){paused=!paused;sync()}};$('speedBtn').onclick=()=>{speed=speed===3?1:speed+1;sync()};$('resetBtn').onclick=()=>showModal('RESET RUN?','POWER, battlefield and Chapter progress reset. ENERGY/unlocks remain safe.','RESET',reset,'CANCEL',closeModal);$('coreUpgrade').onclick=coreUpgrade;$('modalPrimary').onclick=()=>modalAction&&modalAction();$('devToggle').onclick=()=>{if(profile.dev){profile.dev=false;save();log('STANDARD progression restored.');sync();return}showModal('DEV ACCESS','<input id="modalDevCode" type="password" placeholder="ACCESS CODE" style="width:100%;padding:9px;background:#030712;color:#fff;border:1px solid #2eeaff">','AUTHORIZE',()=>{let v=$('modalDevCode').value.trim().toUpperCase();if(v===DEV){profile.dev=true;save();closeModal();log('DEV MODE enabled.');sync()}else{$('modalText').insertAdjacentHTML('beforeend','<div style="color:#ff3e7a;margin-top:8px">ACCESS DENIED</div>')}},'CANCEL',closeModal)};
function frame(n){let dt=Math.min((n-last)/1000,.05)*speed;last=n;update(dt);draw();requestAnimationFrame(frame)}reset();requestAnimationFrame(frame);
})();